#!/usr/bin/env python3
"""Flatten the model into one self-contained file for MakerWorld's Parametric Model Maker (single file, OpenSCAD 2021.01):
   ../lib/shape.scad + ../lib/fit.scad + shroud.scad + the print poses from print_layout.scad, with a `part` selector and
   a curated set of customizer parameters at the top (everything else is under [Hidden]). Output: shroud_makerworld.scad.
   Re-run after any change to shroud.scad, print_layout.scad or ../lib/."""
import re, pathlib
here = pathlib.Path(__file__).parent
lib = (here / "../lib/shape.scad").read_text() + "\n" + (here / "../lib/fit.scad").read_text()
model = (here / "shroud.scad").read_text()
layout = (here / "print_layout.scad").read_text()

# customizer header: (name, value, comment) -- the value here replaces the assignment in the body
HEADER = """\
// G.I. Joe Killer W.H.A.L.E. (1984) fan shroud, steering vanes, fan: MakerWorld customizer build.
// GENERATED by build_makerworld.py from shroud.scad + print_layout.scad + lib/ -- edit those, not this file.
// Source, README and the full parameter set: https://github.com/redswoop/gi-joe-killer-whale (shroud/)

/* [Part] */
// Which piece to generate, in its printing pose ("assembly" is a preview only, do not print it)
part = "shroud"; // [shroud:Shroud with the vane roots (base down; supports under the root bars), fin_right:Right vane plate (on its long edge), fin_left:Left vane plate (on its long edge), slat:Slat (print two), tie_bar:Tie bar (knurl up), strut:Strut / hub bar (standing on one ear; brim), fan:Fan (flat), shaft:Fan shaft (on its flat), assembly:Whole assembly (preview only), vane_right:Right vane with root (teeth variant only), vane_left:Left vane with root (teeth variant only)]

/* [Design variant] */
// fused = the vane roots are part of the shroud, plates and slats go on with filament pins (the published design). teeth = loose vanes that key into the rim (older; prints fin+root as one piece with a printed hinge pin)
vane_mount = "fused"; // [fused, teeth]
// fused only: fair the posts with the dart and canoe shapes (false = bare posts)
fused_canoes = true;
// teeth only: how the vane's -Y end grabs the rim
ny_mount = "fork"; // [fork, saddle]
// teeth only: print-in-place pin, or a hole for a length of 1.75 mm filament
hinge_pin = "printed"; // [printed, filament]
// fused only: plate print pose. edge = standing on its long outer edge, knuckles up (best); vertical = on its -Y end
fin_print = "edge"; // [edge, vertical]

/* [Fit and tolerances, mm per side] */
// Hinge knuckle hole on the 1.75 mm filament pin (0.15 was the best of 0.10 / 0.15 / 0.20)
fil_clr = 0.15; // [0.05:0.01:0.40]
// Slat barrel hole on its filament axle (snugger than the hinge so the slats stay put)
slat_fil_clr = 0.10; // [0.00:0.01:0.40]
// Strut ears in the shroud's pockets
ear_clr = 0.2; // [0.05:0.01:0.50]
// Shaft in the fan hub's D socket
shaft_clr = 0.10; // [0.00:0.01:0.40]
// Tie bar eye on the vane pins
tie_eye_clr = 0.2; // [0.05:0.01:0.50]
// Shroud tab: shorten the hook stem by this much so it bites the Whale's lip (0.7 held best)
tab_grip = 0.7; // [0.0:0.05:1.5]
// teeth only: printed hinge pin to hole
hinge_clr = 0.15; // [0.05:0.01:0.50]
// teeth only: fork dart slot to the rim wall (radial)
tooth_clr = 0.10; // [0.00:0.01:0.40]
// teeth only: slat rod in the root bar's hole
slat_clr = 0.15; // [0.05:0.01:0.50]

/* [Fan] */
// Blade handedness: 1 or -1 mirrors the fan for the other spin direction
blade_hand = 1; // [1, -1]
// Extra shaft length beyond the reference's 65 mm reach
shaft_extra = 0; // [0:0.5:10]

/* [Hidden] */
vane_pose = "vertical";
show_ghost = false; show_shroud = false; show_strut = false; show_vanes = false; show_fan = false;
"""
code_only = "\n".join(l for l in HEADER.splitlines() if not l.lstrip().startswith("//"))
names = re.findall(r"(?:^|;)[ \t]*(\w+)\s*=", code_only, re.M)

body = model
body = re.sub(r"^use <[^>]+>.*$", "// (library inlined above)", body, flags=re.M)
for n in names:
    # statement anywhere on a line: `name = value;` -> a note; leaves other statements and comments on the line intact
    body, k = re.subn(r"(^|(?<=;))([ \t]*)%s\s*=\s*[^;]*;" % re.escape(n), r"\2/* %s: see the top of the file */" % n, body, flags=re.M)
    if n not in ("vane_pose", "part"):
        assert k == 1, (n, k)
# drop the original assembly block
i = body.index("if (show_ghost)")
body = body[:i] + """// ---------- assembly preview (part = "assembly") ----------
module assembly() {
    color("SteelBlue") shroud();
    color("Goldenrod") strut();
    color("IndianRed")  vane_roots();
    color("Salmon")     vane_fins();
    color("LightCoral") tie_bar_placed();
    color("Peru")       slats();
    color("DarkSeaGreen") fan_placed();
    color("Olive")        shaft_placed();
}
"""
# print poses: everything after the include/switch lines
j = layout.index("module vane_print")
poses = layout[j:]
poses += """if (part == "assembly")   assembly();
if (fused && (part == "vane_right" || part == "vane_left")) echo("NOTE: vane_right / vane_left are the teeth variant; with vane_mount = fused print the shroud (roots included) and fin_right / fin_left instead.");
if (!fused && part == "shroud") echo("NOTE: teeth variant: the shroud has no vane roots; print vane_right / vane_left as well.");
"""
out = HEADER + "\n// ================= lib/shape.scad + lib/fit.scad =================\n" + lib + \
      "\n// ================= shroud.scad =================\n" + body + \
      "\n// ================= print poses (print_layout.scad) =================\n" + poses
(here / "shroud_makerworld.scad").write_text(out)
print("wrote shroud_makerworld.scad,", out.count("\n"), "lines")
